   const REDIRECT = 302
   const BAD_REQUEST = 400
   const UNAUTHORIZED = 401
   const FORBIDDEN = 403
   const NOT_FOUND = 404
   const CONFLICTING_ERROR = 409
   const VALIDATION_ERROR = 422
   const INTERNAL_SERVER_ERROR = 500

   export default {REDIRECT, BAD_REQUEST,UNAUTHORIZED, FORBIDDEN,NOT_FOUND
   , CONFLICTING_ERROR, VALIDATION_ERROR, INTERNAL_SERVER_ERROR,
   }